---
kind: pipeline
type: docker
name: Build

steps:
- name: Build Image
  image: plugins/docker
  settings:
    repo: floatcms/ssh
    auto_tag: true
    username:
      from_secret: username
    password:
      from_secret: password

trigger:
  branch:
      - master
  event:
      - push